name: Auto Release Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 🧳 Zip extension files
        run: |
          zip -r tiktok-link-extractor.zip \
            manifest.json \
            background.js \
            content.js \
            popup.html \
            popup.js \
            icon.png \
            -x "*.DS_Store"

      - name: 🚀 Create GitHub release & upload zip
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: tiktok-link-extractor.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}